import { chromium } from 'playwright';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, 'output');
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ viewport: { width: 1500, height: 950 }, deviceScaleFactor: 1.5 });
const p = await ctx.newPage();
await p.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await p.evaluate(() => localStorage.clear());
await p.reload({ waitUntil: 'networkidle' });
await p.locator('.x-banner').first().waitFor();
await p.click('#startBlank');
await p.waitForTimeout(250);
await p.click('#btnHelp');
await p.waitForTimeout(300);
await p.screenshot({ path: path.join(OUT, 'tour_step1.png') });
await p.click('.tour-next'); await p.waitForTimeout(250);
await p.screenshot({ path: path.join(OUT, 'tour_step2.png') });
await b.close();
console.log('saved');
