import { chromium } from 'playwright';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(__dirname, 'output');
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ viewport: { width: 1500, height: 1100 }, deviceScaleFactor: 1.5 });
const p = await ctx.newPage();
await p.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await p.evaluate(() => localStorage.clear());
await p.reload({ waitUntil: 'networkidle' });
await p.locator('.x-banner').first().waitFor();
await p.click('#startBlank');
await p.waitForTimeout(300);
await p.locator('[data-tour="polish"]').screenshot({ path: path.join(OUT, 'ui_polish.png') });
// 제품 피커
await p.click('#btnHome');
await p.setInputFiles('#pdfFile', path.join(ROOT, '참고자료', '일룸 프리미엄샵 논현 디에이치 방배 입주 공략의건.pdf'));
await p.waitForFunction(() => document.querySelector('#caseBadge')?.textContent?.includes('case-c'), { timeout: 15000 }).catch(()=>{});
await p.evaluate(() => document.fonts.ready);
await p.waitForTimeout(400);
await p.click('#bannerRoot .product-card');
await p.waitForTimeout(200);
await p.click('[data-imgpick]');
await p.waitForTimeout(300);
await p.locator('.img-picker-card').screenshot({ path: path.join(OUT, 'ui_picker.png') });
await b.close();
console.log('shots saved');
